"""
producer.py  (Producer Repo — Account A)
─────────────────────────────────────────────────────────────────────────────
Runs ONCE PER DAY via GitHub Actions cron (03:00 AM PKT).

Architecture change: state.json → Supabase
  - processed video IDs  → processed_videos table
  - clip metadata        → clips table
  - clip .mp4 files      → Supabase Storage bucket "clips"
  - daily slot log       → daily_slots table  (managed by uploader repo)

This script does NOT upload anything to TikTok — that's uploader.py's job
in the separate Uploader Repo (Account B).

Env vars expected (GitHub Secrets — Producer Repo):
  SUPABASE_URL          – https://yourproject.supabase.co
  SUPABASE_SERVICE_KEY  – service_role key (full DB + Storage access)
  YOUTUBE_API_KEY       – YouTube Data API v3 key
  YOUTUBE_COOKIES_JSON  – JSON array of YouTube session cookies
  YOUTUBE_COOKIES_TXT   – alternative: raw Netscape cookies.txt (fallback)

GitHub Variables (Producer Repo):
  YT_CHANNEL            – e.g. "@somechannel"
  MAX_VIDEOS_PER_RUN    – safety cap, default 5
"""

import json
import os
import random
import subprocess
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import supabase_client as sc
import youtube_api

CLIPS_DIR = Path("clips")
DOWNLOADS_DIR = Path("downloads")
COOKIES_PATH = Path("youtube_cookies.txt")
LOOKBACK_DAYS = 150
PLAYLIST_SCAN_LIMIT = 80
MIN_PART_SECONDS = 40
MAX_PART_SECONDS = 55
MAX_VIDEOS_PER_RUN = int(os.environ.get("MAX_VIDEOS_PER_RUN", "5"))

LOW_QUEUE_THRESHOLD = 2
FAST_PATH_COUNT = 2


def run(cmd: list[str], timeout: int = 600, **kwargs) -> subprocess.CompletedProcess:
    print(f"$ {' '.join(cmd)}")
    return subprocess.run(cmd, check=True, timeout=timeout, **kwargs)


def cookie_args() -> list[str]:
    if COOKIES_PATH.exists():
        return ["--cookies", str(COOKIES_PATH)]
    return []


def _json_cookies_to_netscape(raw_json: str) -> str:
    try:
        cookies = json.loads(raw_json)
    except json.JSONDecodeError as e:
        raise ValueError(f"YOUTUBE_COOKIES_JSON is not valid JSON: {e}")

    if not isinstance(cookies, list):
        raise ValueError("YOUTUBE_COOKIES_JSON must be a JSON array of cookie objects.")

    lines = ["# Netscape HTTP Cookie File", "# Generated by producer.py from YOUTUBE_COOKIES_JSON"]

    for c in cookies:
        domain = c.get("domain", "")
        if not domain:
            continue
        host_only = c.get("hostOnly", False)
        include_subdomains = "FALSE" if host_only else "TRUE"
        path = c.get("path", "/") or "/"
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expiry_raw = c.get("expirationDate", c.get("expires"))
        try:
            expiry = str(int(float(expiry_raw))) if expiry_raw else "2147483647"
        except (TypeError, ValueError):
            expiry = "2147483647"
        name = c.get("name", "")
        value = c.get("value", "")
        if not name:
            continue
        lines.append("\t".join([domain, include_subdomains, path, secure, expiry, name, value]))

    if len(lines) <= 2:
        raise ValueError(
            "YOUTUBE_COOKIES_JSON parsed to zero usable cookies — check the "
            "export included 'domain' and 'name' fields for each cookie."
        )
    return "\n".join(lines) + "\n"


def write_cookies_file() -> bool:
    json_raw = os.environ.get("YOUTUBE_COOKIES_JSON", "").strip()
    if json_raw:
        try:
            netscape_text = _json_cookies_to_netscape(json_raw)
        except ValueError as e:
            print(f"::error::Failed to convert YOUTUBE_COOKIES_JSON: {e}")
            return False
        COOKIES_PATH.write_text(netscape_text, encoding="utf-8")
        cookie_count = netscape_text.count("\n") - 2
        print(f"🍪 Converted YOUTUBE_COOKIES_JSON -> {COOKIES_PATH} ({cookie_count} cookies).")
        return True

    txt_raw = os.environ.get("YOUTUBE_COOKIES_TXT", "").strip()
    if txt_raw:
        COOKIES_PATH.write_text(txt_raw, encoding="utf-8")
        print(f"🍪 Wrote {COOKIES_PATH} ({len(txt_raw)} bytes) from YOUTUBE_COOKIES_TXT.")
        return True

    print("⚠️  Neither YOUTUBE_COOKIES_JSON nor YOUTUBE_COOKIES_TXT is set — "
          "proceeding without cookies.")
    return False


def get_new_videos_via_api(channel: str) -> list[dict]:
    channel_info = youtube_api.resolve_channel(channel)
    if not channel_info:
        print(f"⚠️  Could not resolve channel '{channel}' via YouTube API.")
        return []

    print(f"📡 Resolved channel -> {channel_info['channel_id']}")
    video_ids = youtube_api.list_uploaded_video_ids(
        channel_info["uploads_playlist_id"], max_results=PLAYLIST_SCAN_LIMIT
    )
    if not video_ids:
        print("⚠️  No videos returned from the channel's uploads playlist.")
        return []

    metadata = youtube_api.fetch_video_metadata(video_ids)
    now = datetime.now(timezone.utc)
    window_start = now - timedelta(days=LOOKBACK_DAYS)
    dated_videos = []
    oldest_resolved_dt = None

    for video_id in video_ids:
        meta = metadata.get(video_id)
        if not meta or not meta.get("upload_date"):
            print(f"  ⚠️  No metadata/date returned for {video_id}, skipping.")
            continue
        try:
            upload_dt = datetime.strptime(meta["upload_date"], "%Y%m%d").replace(tzinfo=timezone.utc)
        except ValueError:
            continue
        if oldest_resolved_dt is None or upload_dt < oldest_resolved_dt:
            oldest_resolved_dt = upload_dt
        if window_start <= upload_dt <= now:
            dated_videos.append({"id": video_id, "title": meta.get("title", ""), "_upload_dt": upload_dt})

    if oldest_resolved_dt is not None and oldest_resolved_dt > window_start:
        print(f"⚠️  Scan only reaches back to {oldest_resolved_dt.date()}, not full "
              f"{LOOKBACK_DAYS}-day window. Consider raising PLAYLIST_SCAN_LIMIT.")

    dated_videos.sort(key=lambda v: v["_upload_dt"])
    return dated_videos


def download_video(video_id: str) -> Path | None:
    DOWNLOADS_DIR.mkdir(exist_ok=True)
    output_template = str(DOWNLOADS_DIR / f"{video_id}.%(ext)s")
    cmd = [
        "yt-dlp",
        "-f", "bestvideo+bestaudio/best",
        "--merge-output-format", "mp4",
        "--remote-components", "ejs:github",
        *cookie_args(),
        "-o", output_template,
        f"https://www.youtube.com/watch?v={video_id}",
    ]
    try:
        run(cmd, timeout=1200)
    except subprocess.CalledProcessError as e:
        print(f"  ❌ Download failed for {video_id}: {e}")
        return None
    except subprocess.TimeoutExpired:
        print(f"  ❌ Download timed out for {video_id} after 20 minutes.")
        return None
    expected_path = DOWNLOADS_DIR / f"{video_id}.mp4"
    return expected_path if expected_path.exists() else None


def get_duration_seconds(video_path: Path) -> float:
    print(f"  ⏱️  [DIAG] Starting ffprobe duration check for {video_path.name} ...", flush=True)
    cmd = [
        "ffprobe", "-v", "error",
        "-show_entries", "format=duration",
        "-of", "default=noprint_wrappers=1:nokey=1",
        str(video_path),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, check=True, timeout=60)
    duration = float(result.stdout.strip())
    print(f"  ⏱️  [DIAG] ffprobe finished, duration={duration:.1f}s", flush=True)
    return duration


def build_random_segments(total_duration: float) -> list[tuple[float, float]]:
    segments = []
    cursor = 0.0
    while cursor + MIN_PART_SECONDS <= total_duration:
        length = random.uniform(MIN_PART_SECONDS, MAX_PART_SECONDS)
        end = min(cursor + length, total_duration)
        segments.append((cursor, end))
        cursor = end
    return segments


def render_clip_with_overlay(
    source_path: Path,
    start: float,
    end: float,
    part_number: int,
    out_path: Path,
    add_overlay: bool,
) -> bool:
    CLIPS_DIR.mkdir(exist_ok=True)
    duration = end - start
    cmd = [
        "ffmpeg", "-y",
        "-ss", f"{start:.2f}",
        "-i", str(source_path),
        "-t", f"{duration:.2f}",
    ]
    if add_overlay:
        drawtext = (
            f"drawtext="
            f"text='PART {part_number}':"
            f"fontcolor=white:"
            f"fontsize=64:"
            f"fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:"
            f"box=1:boxcolor=black@0.55:boxborderw=20:"
            f"x=(w-text_w)/2:"
            f"y=h*0.12"
        )
        cmd += ["-vf", drawtext]
    cmd += [
        "-c:v", "libx264",
        "-preset", "medium",
        "-crf", "18",
        "-c:a", "aac",
        "-b:a", "192k",
        "-movflags", "+faststart",
        str(out_path),
    ]
    print(f"  🎬 [DIAG] About to run ffmpeg for part {part_number}...", flush=True)
    try:
        run(cmd, capture_output=True, text=True, timeout=300)
        print(f"  🎬 [DIAG] ffmpeg finished for part {part_number}", flush=True)
        return True
    except subprocess.CalledProcessError as e:
        print(f"  ❌ ffmpeg render failed for part {part_number}: {e.stderr[-1500:] if e.stderr else e}")
        return False
    except subprocess.TimeoutExpired:
        print(f"  ❌ ffmpeg render timed out for part {part_number} after 5 minutes.")
        return False


def process_video(sb, video_id: str) -> int:
    """
    Download one video, split into clips with overlays, upload each clip
    to Supabase Storage, and insert a DB row for each clip.
    Returns the number of clips successfully created.
    """
    print(f"\n📥 Downloading {video_id} ...", flush=True)
    video_path = download_video(video_id)
    print(f"  ✅ [DIAG] download_video() returned: {video_path}", flush=True)
    if not video_path:
        return 0

    print(f"  ⏱️  [DIAG] About to call get_duration_seconds()...", flush=True)
    try:
        duration = get_duration_seconds(video_path)
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired, ValueError) as e:
        print(f"  ❌ Could not read duration for {video_id}: {e}")
        video_path.unlink(missing_ok=True)
        return 0

    segments = build_random_segments(duration)
    if not segments:
        print(f"  ⚠️  Video {video_id} too short ({duration:.1f}s) to split, skipping.")
        video_path.unlink(missing_ok=True)
        return 0

    is_multi_part = len(segments) > 1
    if is_multi_part:
        print(f"  🎬 {len(segments)} parts -> overlay ENABLED for all parts.")
    else:
        print(f"  🎬 1 part only -> overlay DISABLED (single clip).")

    CLIPS_DIR.mkdir(exist_ok=True)
    created = 0
    for idx, (start, end) in enumerate(segments, start=1):
        clip_id = f"{video_id}_part{idx}"
        local_path = CLIPS_DIR / f"{clip_id}.mp4"
        storage_path = f"{clip_id}.mp4"

        print(f"  ✂️  Part {idx}/{len(segments)}: {start:.1f}s → {end:.1f}s")
        ok = render_clip_with_overlay(video_path, start, end, idx, local_path, add_overlay=is_multi_part)
        if not ok:
            continue

        # Upload rendered clip to Supabase Storage
        print(f"  ☁️  Uploading {clip_id} to Supabase Storage...", flush=True)
        try:
            sc.upload_clip_to_storage(sb, str(local_path), storage_path)
        except Exception as e:
            print(f"  ❌ Storage upload failed for {clip_id}: {e}")
            local_path.unlink(missing_ok=True)
            continue

        # Insert clip metadata row into DB
        try:
            sc.insert_clip(sb, {
                "clip_id": clip_id,
                "source_video_id": video_id,
                "part_number": idx,
                "total_parts": len(segments),
                "storage_path": storage_path,
            })
        except Exception as e:
            print(f"  ❌ DB insert failed for {clip_id}: {e}")
            local_path.unlink(missing_ok=True)
            continue

        # Clean up local rendered file — it now lives in Supabase Storage
        local_path.unlink(missing_ok=True)
        print(f"  ✅ {clip_id} stored in Supabase.")
        created += 1

    # Clean up the raw downloaded source
    video_path.unlink(missing_ok=True)
    return created


def main() -> None:
    channel = os.environ.get("YT_CHANNEL", "").strip()
    if not channel:
        print("::error::YT_CHANNEL environment variable is not set. Aborting.")
        sys.exit(1)

    if not os.environ.get("YOUTUBE_API_KEY", "").strip():
        print("::error::YOUTUBE_API_KEY environment variable is not set. Aborting.")
        sys.exit(1)

    if not os.environ.get("SUPABASE_URL", "").strip() or not os.environ.get("SUPABASE_SERVICE_KEY", "").strip():
        print("::error::SUPABASE_URL and SUPABASE_SERVICE_KEY must both be set as Secrets. Aborting.")
        sys.exit(1)

    if not write_cookies_file():
        print("::error::No YouTube cookies available — downloads will fail. Aborting.")
        sys.exit(1)

    try:
        _run_pipeline(channel)
    finally:
        COOKIES_PATH.unlink(missing_ok=True)


def _run_pipeline(channel: str) -> None:
    sb = sc.get_client()

    print(f"🔎 Fetching video list for channel: {channel}")
    candidates = get_new_videos_via_api(channel)
    if not candidates:
        print("⚠️  No videos found in the lookback window — check YT_CHANNEL and YOUTUBE_API_KEY.")
        return

    print(f"📋 {len(candidates)} videos in the last {LOOKBACK_DAYS} days (oldest first).")

    # Skip anything already processed
    processed_ids = sc.get_processed_video_ids(sb)
    new_candidates = [v for v in candidates if v["id"] not in processed_ids]
    print(f"🆕 {len(new_candidates)} new videos in window (oldest first).")

    if not new_candidates:
        print("✅ Nothing new to process today.")
        return

    # Fast-path: if pending queue is low, prioritize filling it
    pending_count = sc.count_pending_clips(sb)
    fast_path_active = pending_count < LOW_QUEUE_THRESHOLD

    if fast_path_active:
        fast_count = min(FAST_PATH_COUNT, len(new_candidates))
        print(f"\n🚨 Queue is low ({pending_count} pending clip(s), threshold "
              f"is {LOW_QUEUE_THRESHOLD}) — fast-path: processing {fast_count} video(s) first.")
        fast_path_videos = new_candidates[:fast_count]
        remaining_budget = max(MAX_VIDEOS_PER_RUN - fast_count, 0)
        remaining_videos = new_candidates[fast_count:fast_count + remaining_budget]
        to_process = fast_path_videos + remaining_videos
    else:
        fast_path_videos = []
        to_process = new_candidates[:MAX_VIDEOS_PER_RUN]

    total_new_clips = 0
    for i, v in enumerate(to_process):
        video_id = v["id"]

        if fast_path_active and i < len(fast_path_videos):
            print(f"\n⚡ [FAST-PATH {i + 1}/{len(fast_path_videos)}] Prioritizing {video_id}.")
        elif fast_path_active and i == len(fast_path_videos):
            print(f"\n▶️  Fast-path done — continuing normal batch.")

        clips_made = process_video(sb, video_id)
        total_new_clips += clips_made

        # Mark processed regardless of clip count (so broken videos aren't retried)
        sc.mark_video_processed(sb, video_id)

        if fast_path_active and i < len(fast_path_videos):
            new_pending = sc.count_pending_clips(sb)
            print(f"  📦 Queue refilled to {new_pending} pending clip(s) after fast-path video {i + 1}.")

    print(f"\n✅ Producer run complete. {total_new_clips} new clip(s) added to queue.")
    print(f"📦 Total pending clips in queue: {sc.count_pending_clips(sb)}")


if __name__ == "__main__":
    main()
